<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Category' => '',
  'Create' => '',
  'Create Category' => '创建分类',
  'Create Item' => '',
  'Create ItemSku' => '',
  'ItemSku' => '',
  'List Item' => '',
  'Manage' => '',
  'Manage Category' => '',
  'Manage Item' => '',
  'Manage ItemSku' => '',
  'Sku' => '',
  'Update' => '',
  'Update Category' => '',
  'Update Item' => '',
  'Update ItemSku' => '',
  'View' => '',
  'View ' => '',
  'View Category' => '',
  'View Item' => '',
  'View ItemSku' => '',
);
