<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:04:33.
 */
class Services_JSON_ErrorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Services_JSON_Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Services_JSON_Error;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
