<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:04:35.
 */
class Services_JSONTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Services_JSON
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Services_JSON;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Services_JSON::utf162utf8
     * @todo   Implement testUtf162utf8().
     */
    public function testUtf162utf8()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::utf82utf16
     * @todo   Implement testUtf82utf16().
     */
    public function testUtf82utf16()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::encode
     * @todo   Implement testEncode().
     */
    public function testEncode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::name_value
     * @todo   Implement testName_value().
     */
    public function testName_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::reduce_string
     * @todo   Implement testReduce_string().
     */
    public function testReduce_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::decode
     * @todo   Implement testDecode().
     */
    public function testDecode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Services_JSON::isError
     * @todo   Implement testIsError().
     */
    public function testIsError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
