<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '
                    Please enter the letters as they are shown in the image above.
                    <br/>Letters are not case-sensitive.
                ' => '',
  'Add comment' => '',
  'Approve' => '',
  'Approve this comment?' => '',
  'Cancel' => '',
  'Comment Text' => '',
  'Commented object' => '',
  'Commented object\'s ID' => '',
  'Comments' => '',
  'Create Time' => '',
  'Delete this comment?' => '',
  'Link' => '',
  'Manage' => '',
  'Manage Comments' => '',
  'No comments' => '',
  'Status' => '',
  'This item cann\'t be commentable' => '',
  'Update Time' => '',
  'User Email' => '',
  'User Name' => '',
  'Verification Code' => '',
  'You cannot add a new comment' => '',
  'approve' => '',
  'delete' => '',
);
