<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Item Categories' => '',
  '分类' => '',
  '品牌名' => '',
  '属性值' => '',
  '属性别名' => '',
  '属性名' => '',
  '属性名字' => '',
  '属性类型' => '',
  '属性编号' => '',
  '打折' => '',
  '排序' => '',
  '是否促销' => '',
  '是否关键属性' => '',
  '是否可以多选' => '',
  '是否展示' => '',
  '是否必选' => '',
  '是否必选属性' => '',
  '是否新的' => '',
  '是否最好的' => '',
  '是否热销' => '',
  '是否销售属性' => '',
  '是否颜色属性' => '',
  '父属性' => '',
  '状态' => '',
  '类型' => '',
);
