<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Themes' => '',
  'Admin Users' => '',
  'Category' => '',
  'Create' => '',
  'Create Admin Users' => '',
  'Create Category' => '',
  'Create Currency' => '',
  'Create Languages' => '',
  'Create Menus' => '',
  'Create Themes' => '',
  'Currency' => '',
  'Delete Admin Users' => '',
  'Delete Category' => '',
  'Delete Currency' => '',
  'Delete Languages' => '',
  'Delete Menus' => '',
  'Delete Themes' => '',
  'Languages' => '',
  'List Admin Users' => '',
  'List Currency' => '',
  'List Languages' => '',
  'List Menus' => '',
  'List Themes' => '',
  'Manage' => '',
  'Manage Admin Users' => '',
  'Manage Category' => '',
  'Manage Currency' => '',
  'Manage Languages' => '',
  'Manage Menus' => '',
  'Manage Themes' => '',
  'Menus' => '',
  'Themes' => '',
  'Update' => '',
  'Update Admin Users' => '',
  'Update Category' => '',
  'Update Currency' => '',
  'Update Languages' => '',
  'Update Menus' => '',
  'Update Themes' => '',
  'View Admin Users' => '',
  'View Category' => '',
  'View Currency' => '',
  'View Languages' => '',
  'View Menus' => '',
  'View Themes' => '',
);
