<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:05:07.
 */
class ThumbBaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ThumbBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ThumbBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ThumbBase::importPlugins
     * @todo   Implement testImportPlugins().
     */
    public function testImportPlugins()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getImported
     * @todo   Implement testGetImported().
     */
    public function testGetImported()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getImportedFunctions
     * @todo   Implement testGetImportedFunctions().
     */
    public function testGetImportedFunctions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getErrorMessage
     * @todo   Implement testGetErrorMessage().
     */
    public function testGetErrorMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::setErrorMessage
     * @todo   Implement testSetErrorMessage().
     */
    public function testSetErrorMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getFileName
     * @todo   Implement testGetFileName().
     */
    public function testGetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::setFileName
     * @todo   Implement testSetFileName().
     */
    public function testSetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getFormat
     * @todo   Implement testGetFormat().
     */
    public function testGetFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::setFormat
     * @todo   Implement testSetFormat().
     */
    public function testSetFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::getHasError
     * @todo   Implement testGetHasError().
     */
    public function testGetHasError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ThumbBase::setHasError
     * @todo   Implement testSetHasError().
     */
    public function testSetHasError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
