<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:07:14.
 */
class ImageHelperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ImageHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImageHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ImageHelper::thumb
     * @todo   Implement testThumb().
     */
    public function testThumb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
