<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"YiiWheels" must work in conjunction with "YiiStrap".' => '',
  '"chartOptions.series" is expected to be an array.' => '',
  '"data" attribute cannot be blank' => '',
  '"inputType" attribute must be of type "radio" or "checkbox"' => '',
  '"uploadAction" attribute cannot be blank' => '',
  '"{attribute}" attribute cannot be empty.' => '',
  '"{attribute}" attribute must be defined' => '',
  '"{attribute}" cannot be empty.' => '',
  '"{operation}" is an unsupported class operation.' => '',
  '$pluginOptions["country"] cannot be blank.' => '',
  'Check' => '',
  'Column summary configuration must be an array containing a "type" element.' => '',
  'Display Chart' => '',
  'Display Grid' => '',
  'Invalid request' => '',
  'No files to upload.' => '',
  'No results found.' => '',
  'Not set' => '',
  'Please enable JavaScript to use file uploader.' => '',
  'The "label" of a type must be defined.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => '',
  'Uncheck' => '',
  'Unknown value for attribute "size".' => '',
  'Unsupported "{attribute}" setting.' => '',
  'Unsupported column type. Supported column types are: "{types}"' => '',
  'You need to set the "series" attribute in order to render a chart' => '',
  '{file} has an invalid extension. Valid extension(s): {extensions}.' => '',
  '{file} is empty, please select files again without it.' => '',
  '{file} is too large, maximum file size is {sizeLimit}.' => '',
  '{file} is too small, minimum file size is {minSizeLimit}.' => '',
);
