<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:04:11.
 */
class FTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var F
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new F;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers F::hello
     * @todo   Implement testHello().
     */
    public function testHello()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::rand_color
     * @todo   Implement testRand_color().
     */
    public function testRand_color()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::t
     * @todo   Implement testT().
     */
    public function testT()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::msubstr
     * @todo   Implement testMsubstr().
     */
    public function testMsubstr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::do_mkdir
     * @todo   Implement testDo_mkdir().
     */
    public function testDo_mkdir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::get_order_id
     * @todo   Implement testGet_order_id().
     */
    public function testGet_order_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::script
     * @todo   Implement testScript().
     */
    public function testScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::rgScript
     * @todo   Implement testRgScript().
     */
    public function testRgScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::check2Array
     * @todo   Implement testCheck2Array().
     */
    public function testCheck2Array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::isfile
     * @todo   Implement testIsfile().
     */
    public function testIsfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::setFlash
     * @todo   Implement testSetFlash().
     */
    public function testSetFlash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::hasFlash
     * @todo   Implement testHasFlash().
     */
    public function testHasFlash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::getFlash
     * @todo   Implement testGetFlash().
     */
    public function testGetFlash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::renderFlash
     * @todo   Implement testRenderFlash().
     */
    public function testRenderFlash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::toTree
     * @todo   Implement testToTree().
     */
    public function testToTree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::toTreeHelper
     * @todo   Implement testToTreeHelper().
     */
    public function testToTreeHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::array_values_one
     * @todo   Implement testArray_values_one().
     */
    public function testArray_values_one()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::deleteDir
     * @todo   Implement testDeleteDir().
     */
    public function testDeleteDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::listFile
     * @todo   Implement testListFile().
     */
    public function testListFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::sub
     * @todo   Implement testSub().
     */
    public function testSub()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::getStringLength
     * @todo   Implement testGetStringLength().
     */
    public function testGetStringLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::subString
     * @todo   Implement testSubString().
     */
    public function testSubString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::get_gravatar
     * @todo   Implement testGet_gravatar().
     */
    public function testGet_gravatar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::strip_empty_html
     * @todo   Implement testStrip_empty_html().
     */
    public function testStrip_empty_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::gmtime
     * @todo   Implement testGmtime().
     */
    public function testGmtime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::xml_to_array
     * @todo   Implement testXml_to_array().
     */
    public function testXml_to_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::sg
     * @todo   Implement testSg().
     */
    public function testSg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::objectToArray
     * @todo   Implement testObjectToArray().
     */
    public function testObjectToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::jquery
     * @todo   Implement testJquery().
     */
    public function testJquery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::themeUrl
     * @todo   Implement testThemeUrl().
     */
    public function testThemeUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::baseUrl
     * @todo   Implement testBaseUrl().
     */
    public function testBaseUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::date
     * @todo   Implement testDate().
     */
    public function testDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F::utf8_str
     * @todo   Implement testUtf8_str().
     */
    public function testUtf8_str()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
