<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-24 at 00:04:06.
 */
class PinyinTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Pinyin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pinyin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Pinyin::full
     * @todo   Implement testFull().
     */
    public function testFull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::full2
     * @todo   Implement testFull2().
     */
    public function testFull2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::first
     * @todo   Implement testFirst().
     */
    public function testFirst()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::getHanziInitial
     * @todo   Implement testGetHanziInitial().
     */
    public function testGetHanziInitial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::_Pinyin
     * @todo   Implement test_Pinyin().
     */
    public function test_Pinyin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::_U2_Utf8_Gb
     * @todo   Implement test_U2_Utf8_Gb().
     */
    public function test_U2_Utf8_Gb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pinyin::_Array_Combine
     * @todo   Implement test_Array_Combine().
     */
    public function test_Array_Combine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
